CREATE TABLE "samal-reef_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "samal-reef_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "samal-reef_affiliate_invitation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_affiliate_invitation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"commissionRate" numeric(5, 2) DEFAULT '1.00' NOT NULL,
	"affiliateCode" varchar(50),
	"expiresAt" timestamp with time zone NOT NULL,
	"usedAt" timestamp with time zone,
	"usedBy" varchar(255),
	"createdBy" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "samal-reef_affiliate_invitation_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "samal-reef_affiliate_link" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_affiliate_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(50) NOT NULL,
	"affiliateUserId" varchar(255) NOT NULL,
	"commissionRate" numeric(5, 2) NOT NULL,
	"status" varchar(50) DEFAULT 'ACTIVE' NOT NULL,
	"clickCount" integer DEFAULT 0 NOT NULL,
	"conversionCount" integer DEFAULT 0 NOT NULL,
	"createdBy" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "samal-reef_affiliate_link_code_unique" UNIQUE("code"),
	CONSTRAINT "samal-reef_affiliate_link_affiliateUserId_unique" UNIQUE("affiliateUserId")
);
--> statement-breakpoint
CREATE TABLE "samal-reef_affiliate_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_affiliate_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"defaultCommissionRate" numeric(5, 2) DEFAULT '1.00' NOT NULL,
	"totalEarned" numeric(10, 2) DEFAULT '0.00' NOT NULL,
	"totalPaid" numeric(10, 2) DEFAULT '0.00' NOT NULL,
	"status" varchar(50) DEFAULT 'ACTIVE' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "samal-reef_affiliate_profile_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "samal-reef_affiliate_transaction" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_affiliate_transaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"affiliateLinkId" integer NOT NULL,
	"ownershipId" integer,
	"bookingId" integer,
	"commissionAmount" numeric(10, 2) NOT NULL,
	"commissionRate" numeric(5, 2) NOT NULL,
	"isPaid" boolean DEFAULT false NOT NULL,
	"paidAt" timestamp with time zone,
	"paidBy" varchar(255),
	"notes" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "samal-reef_booking_revenue_cache" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_booking_revenue_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"year" integer NOT NULL,
	"unitId" integer NOT NULL,
	"month" integer NOT NULL,
	"revenue" numeric(12, 2) DEFAULT '0' NOT NULL,
	"bookingCount" integer DEFAULT 0 NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "samal-reef_booking_revenue_cache_meta" (
	"year" integer PRIMARY KEY NOT NULL,
	"lastRefreshedAt" timestamp with time zone NOT NULL,
	"refreshedByUserId" varchar(255),
	"error" text
);
--> statement-breakpoint
CREATE TABLE "samal-reef_booking_unit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_booking_unit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bookingId" integer NOT NULL,
	"unitId" integer NOT NULL,
	"smoobuReservationId" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "samal-reef_booking" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_booking_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"paymentId" integer,
	"userId" varchar(255),
	"guestName" varchar(255) NOT NULL,
	"guestEmail" varchar(255) NOT NULL,
	"guestPhone" varchar(50),
	"guestCountry" varchar(100),
	"numberOfGuests" integer DEFAULT 1 NOT NULL,
	"collectionId" integer NOT NULL,
	"unitsRequired" integer DEFAULT 1 NOT NULL,
	"checkIn" date NOT NULL,
	"checkOut" date NOT NULL,
	"nightlyRate" numeric(10, 2) NOT NULL,
	"totalNights" integer NOT NULL,
	"subtotal" numeric(10, 2) NOT NULL,
	"cleaningFee" numeric(10, 2) DEFAULT '0.00' NOT NULL,
	"serviceFee" numeric(10, 2) DEFAULT '0.00' NOT NULL,
	"totalPrice" numeric(10, 2) NOT NULL,
	"currency" varchar(10) DEFAULT 'PHP' NOT NULL,
	"status" varchar(50) DEFAULT 'PENDING_PAYMENT' NOT NULL,
	"source" varchar(50) DEFAULT 'DIRECT' NOT NULL,
	"guestNotes" text,
	"internalNotes" text,
	"affiliateLinkId" integer,
	"affiliateDiscount" numeric(10, 2),
	"cancelledAt" timestamp with time zone,
	"cancelledBy" varchar(255),
	"cancellationReason" text,
	"approvalStatus" varchar(50),
	"createdByUserId" varchar(255),
	"approvedByUserId" varchar(255),
	"approvedAt" timestamp with time zone,
	"rejectionReason" varchar(500),
	"confirmedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "samal-reef_collection_discount" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_collection_discount_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"collectionId" integer NOT NULL,
	"label" varchar(100) NOT NULL,
	"percent" numeric(5, 2) NOT NULL,
	"conditionType" varchar(50) DEFAULT 'ALWAYS' NOT NULL,
	"conditionValue" text,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "samal-reef_investor_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_investor_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"totalInvested" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"totalUnitsOwned" integer DEFAULT 0 NOT NULL,
	"phoneNumber" varchar(50),
	"address" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "samal-reef_investor_profile_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "samal-reef_manual_payment_method" (
	"id" varchar(50) PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"instructions" text NOT NULL,
	"accountNumber" varchar(100),
	"accountName" varchar(200),
	"qrCodeUrl" varchar(500),
	"isActive" boolean DEFAULT true NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "samal-reef_ownership" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_ownership_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unitId" integer,
	"userId" varchar(255),
	"pendingInvestorEmail" varchar(255),
	"pendingInvestorName" varchar(255),
	"pricingTierId" integer NOT NULL,
	"percentageOwned" integer NOT NULL,
	"purchasePrice" numeric(10, 2) NOT NULL,
	"paymentMethod" varchar(20) NOT NULL,
	"currency" varchar(10) DEFAULT 'PHP' NOT NULL,
	"affiliateLinkId" integer,
	"paymentId" integer,
	"moaUrl" varchar(500),
	"isSigned" boolean DEFAULT false NOT NULL,
	"moaSignedAt" timestamp with time zone,
	"signerName" varchar(255),
	"certificateUrl" varchar(500),
	"certificateGeneratedAt" timestamp with time zone,
	"approvalStatus" varchar(50),
	"createdByUserId" varchar(255),
	"approvedByUserId" varchar(255),
	"approvedAt" timestamp with time zone,
	"rejectionReason" varchar(500),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "samal-reef_payment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" varchar(50) NOT NULL,
	"externalId" varchar(255) NOT NULL,
	"userId" varchar(255),
	"amount" numeric(10, 2) NOT NULL,
	"currency" varchar(10) NOT NULL,
	"status" varchar(50) NOT NULL,
	"collectionId" integer,
	"pricingTierId" integer,
	"percentageToBuy" integer,
	"affiliateLinkId" integer,
	"manualPaymentMethodId" varchar(50),
	"proofImageUrl" varchar(500),
	"reviewedAt" timestamp with time zone,
	"reviewedBy" varchar(255),
	"rejectionReason" text,
	"metadata" json,
	"webhookProcessedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "samal-reef_payment_externalId_unique" UNIQUE("externalId")
);
--> statement-breakpoint
CREATE TABLE "samal-reef_pricing_tier" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_pricing_tier_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"collectionId" integer NOT NULL,
	"percentage" integer NOT NULL,
	"cryptoPrice" numeric(10, 2) NOT NULL,
	"fiatPrice" numeric(10, 2) NOT NULL,
	"displayLabel" varchar(50) NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"effectiveFrom" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"effectiveUntil" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "samal-reef_property_collection" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_property_collection_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"imageUrl" varchar(500),
	"location" varchar(255),
	"address" varchar(500),
	"city" varchar(255),
	"country" varchar(255),
	"construction" varchar(255),
	"manager" varchar(255),
	"managerPosition" varchar(255),
	"monthlyFee" varchar(255),
	"isActive" boolean DEFAULT true NOT NULL,
	"displayOrder" integer DEFAULT 0 NOT NULL,
	"bookingPricePerNight" numeric(10, 2),
	"bookingCleaningFee" numeric(10, 2) DEFAULT '50.00',
	"bookingServiceFeePercent" numeric(5, 2) DEFAULT '10.00',
	"bookingMinNights" integer DEFAULT 1,
	"bookingMaxGuests" integer DEFAULT 6,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "samal-reef_property_collection_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "samal-reef_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "samal-reef_unit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_unit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"collectionId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"imageUrl" varchar(500),
	"status" varchar(50) DEFAULT 'AVAILABLE' NOT NULL,
	"smoobuApartmentId" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "samal-reef_unit_smoobuApartmentId_unique" UNIQUE("smoobuApartmentId")
);
--> statement-breakpoint
CREATE TABLE "samal-reef_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"role" varchar(50) DEFAULT 'VISITOR' NOT NULL,
	"status" varchar(50) DEFAULT 'ACTIVE' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "samal-reef_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "samal-reef_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "samal-reef_account" ADD CONSTRAINT "samal-reef_account_userId_samal-reef_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_affiliate_invitation" ADD CONSTRAINT "samal-reef_affiliate_invitation_usedBy_samal-reef_user_id_fk" FOREIGN KEY ("usedBy") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_affiliate_invitation" ADD CONSTRAINT "samal-reef_affiliate_invitation_createdBy_samal-reef_user_id_fk" FOREIGN KEY ("createdBy") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_affiliate_link" ADD CONSTRAINT "samal-reef_affiliate_link_affiliateUserId_samal-reef_user_id_fk" FOREIGN KEY ("affiliateUserId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_affiliate_link" ADD CONSTRAINT "samal-reef_affiliate_link_createdBy_samal-reef_user_id_fk" FOREIGN KEY ("createdBy") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_affiliate_profile" ADD CONSTRAINT "samal-reef_affiliate_profile_userId_samal-reef_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."samal-reef_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_affiliate_transaction" ADD CONSTRAINT "samal-reef_affiliate_transaction_affiliateLinkId_samal-reef_affiliate_link_id_fk" FOREIGN KEY ("affiliateLinkId") REFERENCES "public"."samal-reef_affiliate_link"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_affiliate_transaction" ADD CONSTRAINT "samal-reef_affiliate_transaction_ownershipId_samal-reef_ownership_id_fk" FOREIGN KEY ("ownershipId") REFERENCES "public"."samal-reef_ownership"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_affiliate_transaction" ADD CONSTRAINT "samal-reef_affiliate_transaction_bookingId_samal-reef_booking_id_fk" FOREIGN KEY ("bookingId") REFERENCES "public"."samal-reef_booking"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_affiliate_transaction" ADD CONSTRAINT "samal-reef_affiliate_transaction_paidBy_samal-reef_user_id_fk" FOREIGN KEY ("paidBy") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking_revenue_cache" ADD CONSTRAINT "samal-reef_booking_revenue_cache_unitId_samal-reef_unit_id_fk" FOREIGN KEY ("unitId") REFERENCES "public"."samal-reef_unit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking_revenue_cache_meta" ADD CONSTRAINT "samal-reef_booking_revenue_cache_meta_refreshedByUserId_samal-reef_user_id_fk" FOREIGN KEY ("refreshedByUserId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking_unit" ADD CONSTRAINT "samal-reef_booking_unit_bookingId_samal-reef_booking_id_fk" FOREIGN KEY ("bookingId") REFERENCES "public"."samal-reef_booking"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking_unit" ADD CONSTRAINT "samal-reef_booking_unit_unitId_samal-reef_unit_id_fk" FOREIGN KEY ("unitId") REFERENCES "public"."samal-reef_unit"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking" ADD CONSTRAINT "samal-reef_booking_paymentId_samal-reef_payment_id_fk" FOREIGN KEY ("paymentId") REFERENCES "public"."samal-reef_payment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking" ADD CONSTRAINT "samal-reef_booking_userId_samal-reef_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking" ADD CONSTRAINT "samal-reef_booking_collectionId_samal-reef_property_collection_id_fk" FOREIGN KEY ("collectionId") REFERENCES "public"."samal-reef_property_collection"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking" ADD CONSTRAINT "samal-reef_booking_affiliateLinkId_samal-reef_affiliate_link_id_fk" FOREIGN KEY ("affiliateLinkId") REFERENCES "public"."samal-reef_affiliate_link"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking" ADD CONSTRAINT "samal-reef_booking_cancelledBy_samal-reef_user_id_fk" FOREIGN KEY ("cancelledBy") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking" ADD CONSTRAINT "samal-reef_booking_createdByUserId_samal-reef_user_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_booking" ADD CONSTRAINT "samal-reef_booking_approvedByUserId_samal-reef_user_id_fk" FOREIGN KEY ("approvedByUserId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_collection_discount" ADD CONSTRAINT "samal-reef_collection_discount_collectionId_samal-reef_property_collection_id_fk" FOREIGN KEY ("collectionId") REFERENCES "public"."samal-reef_property_collection"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_investor_profile" ADD CONSTRAINT "samal-reef_investor_profile_userId_samal-reef_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."samal-reef_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_ownership" ADD CONSTRAINT "samal-reef_ownership_unitId_samal-reef_unit_id_fk" FOREIGN KEY ("unitId") REFERENCES "public"."samal-reef_unit"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_ownership" ADD CONSTRAINT "samal-reef_ownership_userId_samal-reef_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_ownership" ADD CONSTRAINT "samal-reef_ownership_pricingTierId_samal-reef_pricing_tier_id_fk" FOREIGN KEY ("pricingTierId") REFERENCES "public"."samal-reef_pricing_tier"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_ownership" ADD CONSTRAINT "samal-reef_ownership_affiliateLinkId_samal-reef_affiliate_link_id_fk" FOREIGN KEY ("affiliateLinkId") REFERENCES "public"."samal-reef_affiliate_link"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_ownership" ADD CONSTRAINT "samal-reef_ownership_paymentId_samal-reef_payment_id_fk" FOREIGN KEY ("paymentId") REFERENCES "public"."samal-reef_payment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_ownership" ADD CONSTRAINT "samal-reef_ownership_createdByUserId_samal-reef_user_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_ownership" ADD CONSTRAINT "samal-reef_ownership_approvedByUserId_samal-reef_user_id_fk" FOREIGN KEY ("approvedByUserId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_payment" ADD CONSTRAINT "samal-reef_payment_userId_samal-reef_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_payment" ADD CONSTRAINT "samal-reef_payment_collectionId_samal-reef_property_collection_id_fk" FOREIGN KEY ("collectionId") REFERENCES "public"."samal-reef_property_collection"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_payment" ADD CONSTRAINT "samal-reef_payment_pricingTierId_samal-reef_pricing_tier_id_fk" FOREIGN KEY ("pricingTierId") REFERENCES "public"."samal-reef_pricing_tier"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_payment" ADD CONSTRAINT "samal-reef_payment_affiliateLinkId_samal-reef_affiliate_link_id_fk" FOREIGN KEY ("affiliateLinkId") REFERENCES "public"."samal-reef_affiliate_link"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_payment" ADD CONSTRAINT "samal-reef_payment_manualPaymentMethodId_samal-reef_manual_payment_method_id_fk" FOREIGN KEY ("manualPaymentMethodId") REFERENCES "public"."samal-reef_manual_payment_method"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_payment" ADD CONSTRAINT "samal-reef_payment_reviewedBy_samal-reef_user_id_fk" FOREIGN KEY ("reviewedBy") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_pricing_tier" ADD CONSTRAINT "samal-reef_pricing_tier_collectionId_samal-reef_property_collection_id_fk" FOREIGN KEY ("collectionId") REFERENCES "public"."samal-reef_property_collection"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_session" ADD CONSTRAINT "samal-reef_session_userId_samal-reef_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_unit" ADD CONSTRAINT "samal-reef_unit_collectionId_samal-reef_property_collection_id_fk" FOREIGN KEY ("collectionId") REFERENCES "public"."samal-reef_property_collection"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "samal-reef_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "invitation_token_idx" ON "samal-reef_affiliate_invitation" USING btree ("token");--> statement-breakpoint
CREATE INDEX "invitation_email_idx" ON "samal-reef_affiliate_invitation" USING btree ("email");--> statement-breakpoint
CREATE INDEX "affiliate_link_code_idx" ON "samal-reef_affiliate_link" USING btree ("code");--> statement-breakpoint
CREATE INDEX "affiliate_link_user_idx" ON "samal-reef_affiliate_link" USING btree ("affiliateUserId");--> statement-breakpoint
CREATE INDEX "affiliate_user_idx" ON "samal-reef_affiliate_profile" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "transaction_affiliate_idx" ON "samal-reef_affiliate_transaction" USING btree ("affiliateLinkId");--> statement-breakpoint
CREATE INDEX "transaction_ownership_idx" ON "samal-reef_affiliate_transaction" USING btree ("ownershipId");--> statement-breakpoint
CREATE INDEX "transaction_booking_idx" ON "samal-reef_affiliate_transaction" USING btree ("bookingId");--> statement-breakpoint
CREATE INDEX "transaction_paid_idx" ON "samal-reef_affiliate_transaction" USING btree ("isPaid");--> statement-breakpoint
CREATE INDEX "revenue_cache_year_idx" ON "samal-reef_booking_revenue_cache" USING btree ("year");--> statement-breakpoint
CREATE INDEX "revenue_cache_unit_month_idx" ON "samal-reef_booking_revenue_cache" USING btree ("unitId","month");--> statement-breakpoint
CREATE INDEX "booking_unit_booking_idx" ON "samal-reef_booking_unit" USING btree ("bookingId");--> statement-breakpoint
CREATE INDEX "booking_unit_unit_idx" ON "samal-reef_booking_unit" USING btree ("unitId");--> statement-breakpoint
CREATE INDEX "booking_payment_idx" ON "samal-reef_booking" USING btree ("paymentId");--> statement-breakpoint
CREATE INDEX "booking_user_idx" ON "samal-reef_booking" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "booking_collection_idx" ON "samal-reef_booking" USING btree ("collectionId");--> statement-breakpoint
CREATE INDEX "booking_status_idx" ON "samal-reef_booking" USING btree ("status");--> statement-breakpoint
CREATE INDEX "booking_dates_idx" ON "samal-reef_booking" USING btree ("checkIn","checkOut");--> statement-breakpoint
CREATE INDEX "booking_source_idx" ON "samal-reef_booking" USING btree ("source");--> statement-breakpoint
CREATE INDEX "booking_approval_status_idx" ON "samal-reef_booking" USING btree ("approvalStatus");--> statement-breakpoint
CREATE INDEX "booking_affiliate_idx" ON "samal-reef_booking" USING btree ("affiliateLinkId");--> statement-breakpoint
CREATE INDEX "collection_discount_collection_idx" ON "samal-reef_collection_discount" USING btree ("collectionId");--> statement-breakpoint
CREATE INDEX "collection_discount_active_idx" ON "samal-reef_collection_discount" USING btree ("collectionId","isActive");--> statement-breakpoint
CREATE INDEX "investor_user_idx" ON "samal-reef_investor_profile" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "manual_payment_method_active_idx" ON "samal-reef_manual_payment_method" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "ownership_unit_idx" ON "samal-reef_ownership" USING btree ("unitId");--> statement-breakpoint
CREATE INDEX "ownership_user_idx" ON "samal-reef_ownership" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "ownership_affiliate_idx" ON "samal-reef_ownership" USING btree ("affiliateLinkId");--> statement-breakpoint
CREATE INDEX "ownership_pricing_tier_idx" ON "samal-reef_ownership" USING btree ("pricingTierId");--> statement-breakpoint
CREATE INDEX "ownership_moa_signed_idx" ON "samal-reef_ownership" USING btree ("isSigned");--> statement-breakpoint
CREATE INDEX "ownership_approval_status_idx" ON "samal-reef_ownership" USING btree ("approvalStatus");--> statement-breakpoint
CREATE INDEX "payment_external_idx" ON "samal-reef_payment" USING btree ("externalId");--> statement-breakpoint
CREATE INDEX "payment_status_idx" ON "samal-reef_payment" USING btree ("status");--> statement-breakpoint
CREATE INDEX "payment_user_idx" ON "samal-reef_payment" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "payment_provider_idx" ON "samal-reef_payment" USING btree ("provider");--> statement-breakpoint
CREATE INDEX "pricing_tier_collection_idx" ON "samal-reef_pricing_tier" USING btree ("collectionId");--> statement-breakpoint
CREATE INDEX "pricing_tier_percentage_idx" ON "samal-reef_pricing_tier" USING btree ("percentage");--> statement-breakpoint
CREATE INDEX "pricing_tier_active_idx" ON "samal-reef_pricing_tier" USING btree ("isActive");--> statement-breakpoint
CREATE UNIQUE INDEX "pricing_tier_collection_percentage_idx" ON "samal-reef_pricing_tier" USING btree ("collectionId","percentage");--> statement-breakpoint
CREATE INDEX "collection_slug_idx" ON "samal-reef_property_collection" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "collection_active_idx" ON "samal-reef_property_collection" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "samal-reef_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "unit_collection_idx" ON "samal-reef_unit" USING btree ("collectionId");--> statement-breakpoint
CREATE INDEX "unit_status_idx" ON "samal-reef_unit" USING btree ("status");--> statement-breakpoint
CREATE INDEX "unit_smoobu_idx" ON "samal-reef_unit" USING btree ("smoobuApartmentId");