CREATE TABLE "samal-reef_gallery_image" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_gallery_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"collectionId" integer NOT NULL,
	"url" varchar(500) NOT NULL,
	"fileKey" varchar(255) NOT NULL,
	"alt" varchar(255),
	"displayOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "samal-reef_gallery_image" ADD CONSTRAINT "samal-reef_gallery_image_collectionId_samal-reef_property_collection_id_fk" FOREIGN KEY ("collectionId") REFERENCES "public"."samal-reef_property_collection"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "gallery_image_collection_idx" ON "samal-reef_gallery_image" USING btree ("collectionId");--> statement-breakpoint
CREATE INDEX "gallery_image_order_idx" ON "samal-reef_gallery_image" USING btree ("collectionId","displayOrder");