CREATE TABLE "samal-reef_quarterly_owner_payout" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_quarterly_owner_payout_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"settlementId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"percentageOwned" integer NOT NULL,
	"amount" numeric(12, 2) DEFAULT '0' NOT NULL,
	"isPaid" boolean DEFAULT false NOT NULL,
	"paidAt" timestamp with time zone,
	"paidBy" varchar(255),
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "samal-reef_quarterly_unit_settlement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "samal-reef_quarterly_unit_settlement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unitId" integer NOT NULL,
	"year" integer NOT NULL,
	"quarter" integer NOT NULL,
	"grossRevenue" numeric(12, 2) DEFAULT '0' NOT NULL,
	"fixedExpense" numeric(12, 2) DEFAULT '0' NOT NULL,
	"additionalExpense" numeric(12, 2) DEFAULT '0' NOT NULL,
	"managementFee" numeric(12, 2) DEFAULT '0' NOT NULL,
	"netPool" numeric(12, 2) DEFAULT '0' NOT NULL,
	"notes" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"createdByUserId" varchar(255)
);
--> statement-breakpoint
ALTER TABLE "samal-reef_quarterly_owner_payout" ADD CONSTRAINT "samal-reef_quarterly_owner_payout_settlementId_samal-reef_quarterly_unit_settlement_id_fk" FOREIGN KEY ("settlementId") REFERENCES "public"."samal-reef_quarterly_unit_settlement"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_quarterly_owner_payout" ADD CONSTRAINT "samal-reef_quarterly_owner_payout_userId_samal-reef_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_quarterly_owner_payout" ADD CONSTRAINT "samal-reef_quarterly_owner_payout_paidBy_samal-reef_user_id_fk" FOREIGN KEY ("paidBy") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_quarterly_unit_settlement" ADD CONSTRAINT "samal-reef_quarterly_unit_settlement_unitId_samal-reef_unit_id_fk" FOREIGN KEY ("unitId") REFERENCES "public"."samal-reef_unit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samal-reef_quarterly_unit_settlement" ADD CONSTRAINT "samal-reef_quarterly_unit_settlement_createdByUserId_samal-reef_user_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."samal-reef_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "payout_settlement_user_idx" ON "samal-reef_quarterly_owner_payout" USING btree ("settlementId","userId");--> statement-breakpoint
CREATE INDEX "payout_settlement_idx" ON "samal-reef_quarterly_owner_payout" USING btree ("settlementId");--> statement-breakpoint
CREATE INDEX "payout_user_idx" ON "samal-reef_quarterly_owner_payout" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "payout_paid_idx" ON "samal-reef_quarterly_owner_payout" USING btree ("isPaid");--> statement-breakpoint
CREATE UNIQUE INDEX "settlement_unit_year_quarter_idx" ON "samal-reef_quarterly_unit_settlement" USING btree ("unitId","year","quarter");--> statement-breakpoint
CREATE INDEX "settlement_unit_year_idx" ON "samal-reef_quarterly_unit_settlement" USING btree ("unitId","year");